/* oxlint-disable react/only-export-components */
import styled from "styled-components";
import { Button, Card, Input, Select } from "../UI";

export const PageHead=styled.div`display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:26px;h2{font-size:1.8rem;letter-spacing:-.04em;margin:0 0 5px}p{color:#6a756d;margin:0}@media(max-width:600px){align-items:flex-start;flex-direction:column}`;
export const AdminCard=styled(Card)`overflow:hidden;`;
export const TableWrap=styled.div`overflow-x:auto;table{width:100%;border-collapse:collapse;min-width:760px}th{text-align:left;background:#f7f8f6;color:#657168;font-size:.75rem;text-transform:uppercase;letter-spacing:.06em;padding:14px 17px}td{padding:15px 17px;border-top:1px solid #e9ede9;vertical-align:middle}.actions{display:flex;gap:7px}.icon-btn{width:36px;height:36px;border:0;border-radius:9px;background:#edf1ed;display:grid;place-items:center;cursor:pointer;color:#355443}.icon-btn.danger{background:#fff0f0;color:#b33636}.thumb{width:50px;height:50px;object-fit:cover;border-radius:9px;background:#edf0ed}.id{font-family:monospace;font-size:.78rem;color:#647068}`;
export const Badge=styled.span`display:inline-flex;padding:6px 9px;border-radius:18px;font-size:.72rem;font-weight:800;background:${({$tone})=>$tone==="danger"?"#fde8e8":$tone==="warning"?"#fff0d8":$tone==="info"?"#e6edf7":"#e4f1e7"};color:${({$tone})=>$tone==="danger"?"#a92f2f":$tone==="warning"?"#925c17":$tone==="info"?"#315f95":"#256c45"};`;
export const Toolbar=styled.div`display:flex;gap:12px;margin-bottom:18px;${Input}{max-width:360px}${Select}{margin-left:auto}`;
export const FormCard=styled(Card)`padding:28px;max-width:820px;.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.field{margin-bottom:18px}.field.full{grid-column:1/-1}.field label{display:block;font-weight:700;font-size:.86rem;margin-bottom:7px}.field small{display:block;color:#748077;margin-top:6px}.checks{display:flex;flex-wrap:wrap;gap:10px}.check{border:1px solid #dae1da;border-radius:10px;padding:10px 12px;display:flex;gap:8px;align-items:center}.preview{width:120px;height:120px;object-fit:cover;border-radius:13px;background:#eef1ed;margin-top:10px}.buttons{display:flex;gap:10px;margin-top:24px}@media(max-width:650px){.grid{grid-template-columns:1fr}}`;
export const ModalBackdrop=styled.div`position:fixed;inset:0;background:rgba(12,28,19,.55);z-index:500;display:grid;place-items:center;padding:20px;`;
export const ModalBox=styled(Card)`width:min(440px,100%);padding:27px;h3{font-size:1.25rem}p{color:#68736b;line-height:1.6}.buttons{display:flex;justify-content:flex-end;gap:10px;margin-top:24px}`;
export function ConfirmModal({title,message,loading,onCancel,onConfirm}){return <ModalBackdrop role="presentation" onMouseDown={onCancel}><ModalBox role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><h3>{title}</h3><p>{message}</p><div className="buttons"><Button $secondary onClick={onCancel} disabled={loading}>Cancelar</Button><Button $danger onClick={onConfirm} disabled={loading}>{loading?"Excluindo...":"Excluir"}</Button></div></ModalBox></ModalBackdrop>}
export const statusTone=status=>status==="CANCELADO"?"danger":status==="AGUARDANDO_PAGAMENTO"?"warning":status==="ENVIADO"?"info":"success";
