import { NavLink, Outlet, Link } from "react-router-dom";
import { Boxes, CreditCard, LayoutDashboard, Package, ShoppingBag, Users } from "lucide-react";
import styled from "styled-components";
import { useAuth } from "../../contexts/AuthContext";

const Shell = styled.div`min-height:100vh;background:#f3f5f2;display:grid;grid-template-columns:260px 1fr;@media(max-width:850px){grid-template-columns:1fr}`;
const Side = styled.aside`background:#153c28;color:white;padding:28px 20px;display:flex;flex-direction:column;position:sticky;top:0;height:100vh;.brand{font:800 1.5rem Manrope;margin:0 12px 35px}.brand span{color:#f0a05a}.label{font-size:.72rem;text-transform:uppercase;letter-spacing:.12em;color:#86a993;margin:0 12px 10px}nav{display:grid;gap:6px}nav a{display:flex;align-items:center;gap:12px;padding:12px 13px;border-radius:11px;color:#c7d9cc;font-weight:600}nav a:hover,nav a.active{background:#285a3e;color:white}.bottom{margin-top:auto;border-top:1px solid #346149;padding-top:18px}.user{padding:0 12px 15px}.user strong,.user small{display:block}.user small{color:#9eb6a6;margin-top:3px}.store{display:flex;align-items:center;gap:9px;padding:11px 12px;color:#c7d9cc}@media(max-width:850px){height:auto;position:static;nav{grid-template-columns:repeat(5,1fr)}nav a{justify-content:center;font-size:0}nav a svg{margin:0}.bottom{display:none}.brand{margin-bottom:20px}}`;
const Main = styled.main`min-width:0;`;
const Header = styled.header`height:78px;background:white;border-bottom:1px solid #e1e6e1;display:flex;align-items:center;justify-content:space-between;padding:0 36px;h1{font-size:1.2rem;margin:0}.badge{background:#e4f0e6;color:#22633f;border-radius:20px;padding:7px 11px;font-size:.76rem;font-weight:800}@media(max-width:600px){padding:0 18px}`;
const Content = styled.div`padding:34px 36px 60px;max-width:1450px;margin:auto;@media(max-width:600px){padding:24px 16px}`;

export default function AdminLayout(){const{user}=useAuth();return <Shell><Side><Link className="brand" to="/admin">nexo<span>.</span> admin</Link><p className="label">Gerenciamento</p><nav><NavLink end to="/admin"><LayoutDashboard/>Dashboard</NavLink><NavLink to="/admin/produtos"><Boxes/>Produtos</NavLink><NavLink to="/admin/usuarios"><Users/>Usuários</NavLink><NavLink to="/admin/pedidos"><Package/>Pedidos</NavLink><NavLink to="/admin/pagamentos"><CreditCard/>Pagamentos</NavLink></nav><div className="bottom"><div className="user"><strong>{user.nome}</strong><small>Administrador</small></div><Link className="store" to="/"><ShoppingBag size={18}/>Voltar para a loja</Link></div></Side><Main><Header><h1>Painel Administrativo</h1><span className="badge">ADMIN</span></Header><Content><Outlet/></Content></Main></Shell>}
