import { Link, useNavigate } from "react-router-dom";
import { Minus, Plus, ShoppingBag, Trash2 } from "lucide-react";
import { useState } from "react";
import styled from "styled-components";
import { useCart } from "../contexts/CartContext";
import { useAuth } from "../contexts/AuthContext";
import { useToast } from "../contexts/ToastContext";
import { createOrder } from "../services/orderService";
import { formatCurrency, getErrorMessage, today } from "../utils/format";
import { Button, Card, Container, EmptyState, Section } from "../components/UI";
const Title=styled.div`background:#e8efe6;padding:44px 0;h1{font-size:2.5rem;margin:0}`;
const Layout=styled.div`display:grid;grid-template-columns:1fr 360px;gap:28px;align-items:start;@media(max-width:850px){grid-template-columns:1fr}`;
const Items=styled.div`display:grid;gap:14px;`;
const Item=styled(Card)`padding:16px;display:grid;grid-template-columns:100px 1fr auto auto;gap:18px;align-items:center;img{width:100px;height:100px;object-fit:cover;border-radius:13px;background:#eef1ed}h3{font-size:1rem;margin-bottom:6px}p{color:#647068;margin:0}.qty{display:flex;align-items:center;border:1px solid #dce2dc;border-radius:10px}.qty button{border:0;background:transparent;padding:8px;cursor:pointer}.qty span{min-width:28px;text-align:center}.remove{border:0;background:#fff1f1;color:#b23131;border-radius:10px;padding:9px;cursor:pointer}@media(max-width:600px){grid-template-columns:75px 1fr;img{width:75px;height:75px}.qty,.remove{grid-column:auto}}`;
const Summary=styled(Card)`padding:25px;position:sticky;top:100px;h2{font-size:1.25rem}.line{display:flex;justify-content:space-between;color:#667168;margin:14px 0}.total{border-top:1px solid #e1e6e1;padding-top:18px;margin-top:18px;color:#17211a;font-weight:800;font-size:1.18rem}${Button}{width:100%;margin-top:15px}.hint{font-size:.82rem;text-align:center;color:#788279;line-height:1.5;margin:13px 0 0}`;
export default function Cart(){const{items,total,updateQuantity,removeItem,clearCart}=useCart();const{user,isAuthenticated}=useAuth();const{showToast}=useToast();const navigate=useNavigate();const[loading,setLoading]=useState(false);const checkout=async()=>{if(!isAuthenticated){showToast("Entre na sua conta para finalizar a compra.","error");navigate("/login",{state:{from:"/carrinho"}});return}if(loading)return;setLoading(true);try{const payload={cliente_id:user.id,momento:today(),status:"AGUARDANDO_PAGAMENTO",items:items.map(item=>({produto_id:item.id,quantidade:item.quantity,preco:Number(item.preco)}))};const order=await createOrder(payload);const id=order.id||order.pedido_id;if(!id)throw new Error("Não foi possível localizar o pedido criado.");clearCart();showToast("Pedido criado com sucesso.");navigate(`/pagamento/${id}`)}catch(error){showToast(getErrorMessage(error,"Não foi possível criar o pedido."),"error")}finally{setLoading(false)}};return <><Title><Container><h1>Seu carrinho</h1></Container></Title><Section><Container>{items.length===0?<EmptyState title="Seu carrinho está vazio" message="Explore o catálogo e encontre algo especial." action={<Button as={Link} to="/produtos"><ShoppingBag size={18}/>Ver produtos</Button>}/>:<Layout><Items>{items.map(item=><Item key={item.id}><img src={item.imgUrl} alt={item.nome}/><div><h3>{item.nome}</h3><p>{formatCurrency(item.preco)}</p></div><div className="qty"><button onClick={()=>updateQuantity(item.id,item.quantity-1)}><Minus size={16}/></button><span>{item.quantity}</span><button onClick={()=>updateQuantity(item.id,item.quantity+1)}><Plus size={16}/></button></div><button className="remove" onClick={()=>removeItem(item.id)} aria-label="Remover"><Trash2 size={18}/></button></Item>)}</Items><Summary><h2>Resumo do pedido</h2><div className="line"><span>Itens</span><span>{items.reduce((n,i)=>n+i.quantity,0)}</span></div><div className="line"><span>Subtotal</span><span>{formatCurrency(total)}</span></div><div className="line total"><span>Total</span><span>{formatCurrency(total)}</span></div><Button onClick={checkout} disabled={loading}>{loading?"Preparando seu pedido...":"Finalizar compra"}</Button><p className="hint">Na próxima etapa, você poderá revisar e confirmar o pagamento.</p></Summary></Layout>}</Container></Section></>}
