import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { CalendarDays, ChevronRight, Package } from "lucide-react";
import styled from "styled-components";
import { getOrders } from "../services/orderService";
import { getPayments } from "../services/paymentService";
import { getProducts } from "../services/productService";
import { useAuth } from "../contexts/AuthContext";
import { Button, Card, Container, EmptyState, ErrorState, Loading, Section } from "../components/UI";
import { formatCurrency, formatDate } from "../utils/format";
const Head=styled.div`background:#e8efe6;padding:46px 0;h1{font-size:2.5rem;margin-bottom:7px}p{color:#657168;margin:0}`;
const Tabs=styled.div`display:flex;gap:8px;margin-bottom:24px;border-bottom:1px solid #dce2dc;button{border:0;background:transparent;padding:12px 15px;cursor:pointer;color:#68736b;font-weight:700;border-bottom:3px solid transparent}.active{color:#1d5c3a;border-color:#1d5c3a}`;
const List=styled.div`display:grid;gap:16px;`;
const Order=styled(Card)`padding:22px;.top{display:flex;justify-content:space-between;gap:20px;align-items:start;border-bottom:1px solid #e9ede9;padding-bottom:17px}.number{font-family:monospace;color:#69746c;font-size:.84rem;word-break:break-all}.status{padding:7px 11px;border-radius:20px;background:${({$pending})=>$pending?"#fff0d8":"#e5f3e8"};color:${({$pending})=>$pending?"#9b611c":"#287047"};font-size:.76rem;font-weight:800}.items{padding:14px 0;color:#606c63}.items p{margin:6px 0}.bottom{display:flex;justify-content:space-between;align-items:center;gap:16px}.date{display:flex;gap:7px;color:#758078;font-size:.88rem}.actions{display:flex;align-items:center;gap:16px}@media(max-width:600px){.top,.bottom{flex-direction:column}.actions{width:100%;justify-content:space-between}}`;
export default function Orders(){const{user}=useAuth();const[orders,setOrders]=useState([]);const[payments,setPayments]=useState([]);const[products,setProducts]=useState([]);const[tab,setTab]=useState("pending");const[loading,setLoading]=useState(true);const[error,setError]=useState("");const load=()=>{setLoading(true);Promise.all([getOrders(),getPayments(),getProducts()]).then(([o,p,pr])=>{setOrders(o.filter(order=>order.cliente_id===user.id));setPayments(p);setProducts(pr)}).catch(()=>setError("Não foi possível carregar seus pedidos.")).finally(()=>setLoading(false))};useEffect(load,[user.id]);const paidIds=useMemo(()=>new Set(payments.map(p=>p.pedido_id)),[payments]);const names=useMemo(()=>Object.fromEntries(products.map(p=>[p.id,p.nome])),[products]);const pending=orders.filter(o=>o.status==="AGUARDANDO_PAGAMENTO"&&!paidIds.has(o.id));const history=orders.filter(o=>o.status!=="AGUARDANDO_PAGAMENTO"||paidIds.has(o.id));const shown=tab==="pending"?pending:history;if(loading)return <Loading text="Carregando pedidos..."/>;return <><Head><Container><h1>Meus pedidos</h1><p>Acompanhe pagamentos e histórico de compras.</p></Container></Head><Section><Container>{error?<ErrorState message={error} onRetry={load}/>:<><Tabs><button className={tab==="pending"?"active":""} onClick={()=>setTab("pending")}>Pendentes ({pending.length})</button><button className={tab==="history"?"active":""} onClick={()=>setTab("history")}>Histórico ({history.length})</button></Tabs>{shown.length===0?<EmptyState title={tab==="pending"?"Nenhum pagamento pendente":"Seu histórico está vazio"} message={tab==="pending"?"Seus pedidos aguardando pagamento aparecerão aqui.":"Quando você comprar, seus pedidos aparecerão aqui."}/>:<List>{shown.map(order=>{const isPending=order.status==="AGUARDANDO_PAGAMENTO"&&!paidIds.has(order.id);return <Order key={order.id} $pending={isPending}><div className="top"><div><strong>Pedido</strong><div className="number">#{order.id}</div></div><span className="status">{isPending?"AGUARDANDO PAGAMENTO":order.status?.replaceAll("_"," ")}</span></div><div className="items">{order.items?.map((item,i)=><p key={i}>{item.quantidade}× {names[item.produto_id]||`Produto ${item.produto_id.slice(0,8)}`}</p>)}</div><div className="bottom"><span className="date"><CalendarDays size={17}/>{formatDate(order.momento)}</span><div className="actions"><strong>{formatCurrency(order.subtotal)}</strong>{isPending?<Button as={Link} to={`/pagamento/${order.id}`}>Pagar agora <ChevronRight size={17}/></Button>:<Package size={20}/>}</div></div></Order>})}</List>}</>}</Container></Section></>}
