import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { CheckCircle2, CreditCard, LockKeyhole } from "lucide-react";
import styled from "styled-components";
import { getOrderById } from "../services/orderService";
import { createPayment, getPayments } from "../services/paymentService";
import { getProducts } from "../services/productService";
import { useAuth } from "../contexts/AuthContext";
import { useToast } from "../contexts/ToastContext";
import { Button, Card, Container, ErrorState, Loading, Section } from "../components/UI";
import { formatCurrency, getErrorMessage, today } from "../utils/format";
const Head=styled.div`background:#173e2a;color:white;padding:46px 0;h1{font-size:2.35rem;margin:0 0 7px}p{color:#c6d8cc;margin:0}`;
const Layout=styled.div`display:grid;grid-template-columns:1fr 380px;gap:28px;align-items:start;@media(max-width:850px){grid-template-columns:1fr}`;
const Box=styled(Card)`padding:26px;h2{font-size:1.25rem}.id{font-family:monospace;background:#f0f3ef;padding:8px 10px;border-radius:8px;word-break:break-all}.item{display:flex;justify-content:space-between;gap:20px;padding:13px 0;border-bottom:1px solid #edf0ed}.muted{color:#6d786f}.status{display:inline-block;padding:7px 11px;border-radius:20px;background:#fff1db;color:#9a5b17;font-weight:700;font-size:.78rem}.total{display:flex;justify-content:space-between;font-size:1.25rem;font-weight:800;margin-top:20px}`;
const PayBox=styled(Box)`position:sticky;top:100px;.method{border:2px solid #4b8e66;border-radius:13px;padding:16px;display:flex;gap:12px;margin:18px 0;background:#f4f8f3}.method p{margin:3px 0 0;color:#6a756d;font-size:.86rem}${Button}{width:100%}.secure{font-size:.83rem;color:#6c776f;text-align:center;display:flex;gap:6px;justify-content:center;margin-top:13px}`;
export default function Payment(){const{pedidoId}=useParams();const{user}=useAuth();const{showToast}=useToast();const navigate=useNavigate();const[order,setOrder]=useState(null);const[payments,setPayments]=useState([]);const[products,setProducts]=useState([]);const[loading,setLoading]=useState(true);const[processing,setProcessing]=useState(false);const[error,setError]=useState("");const load=()=>{setLoading(true);setError("");Promise.all([getOrderById(pedidoId),getPayments(),getProducts()]).then(([o,p,pr])=>{setOrder(o);setPayments(p);setProducts(pr)}).catch(err=>setError(getErrorMessage(err,"Não foi possível consultar este pedido."))).finally(()=>setLoading(false))};useEffect(load,[pedidoId]);const payment=payments.find(p=>p.pedido_id===pedidoId);const belongs=order?.cliente_id===user?.id;const canPay=belongs&&order?.status==="AGUARDANDO_PAGAMENTO"&&!payment;const names=useMemo(()=>Object.fromEntries(products.map(p=>[p.id,p.nome])),[products]);const pay=async()=>{if(!canPay||processing)return;setProcessing(true);try{await createPayment({pedido_id:pedidoId,momento:today()});showToast("Pagamento realizado com sucesso!");await load();setTimeout(()=>navigate("/pedidos"),1200)}catch(err){showToast(getErrorMessage(err,"Não foi possível processar o pagamento."),"error")}finally{setProcessing(false)}};if(loading)return <Loading text="Validando o pedido..."/>;if(error)return <Container><ErrorState message={error} onRetry={load}/></Container>;if(!belongs)return <Container><ErrorState message="Não foi possível acessar este pedido com a conta atual."/></Container>;return <><Head><Container><h1>Pagamento</h1><p>Revise o pedido antes de confirmar.</p></Container></Head><Section><Container><Layout><Box><h2>Resumo do pedido</h2><p className="muted">Número do pedido</p><p className="id">{order.id}</p><p><span className="status">{order.status?.replaceAll("_"," ")}</span></p>{order.items?.map((item,i)=><div className="item" key={`${item.produto_id}-${i}`}><span>{item.quantidade}× {names[item.produto_id]||`Produto ${item.produto_id.slice(0,8)}`}</span><strong>{formatCurrency(item.preco*item.quantidade)}</strong></div>)}<div className="total"><span>Total</span><span>{formatCurrency(order.subtotal)}</span></div></Box><PayBox><h2>Confirmar pagamento</h2>{payment||order.status!=="AGUARDANDO_PAGAMENTO"?<><CheckCircle2 color="#2b7b4d" size={38}/><h3>Este pedido já foi pago ou não aceita um novo pagamento.</h3><p className="muted">Status atual: {order.status?.replaceAll("_"," ")}</p><Button as={Link} to="/pedidos">Voltar aos pedidos</Button></>:<><div className="method"><CreditCard/><div><strong>Pagamento online</strong><p>Confirme abaixo para concluir a sua compra.</p></div></div><Button onClick={pay} disabled={!canPay||processing}>{processing?"Processando pagamento...":`Pagar ${formatCurrency(order.subtotal)}`}</Button><p className="secure"><LockKeyhole size={15}/> Pagamento seguro e confirmação imediata.</p></>}</PayBox></Layout></Container></Section></>}
