import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { LogOut, Mail, Phone, ShieldCheck, UserRound } from "lucide-react";
import styled from "styled-components";
import { useAuth } from "../contexts/AuthContext";
import { Button, Card, Container, Section } from "../components/UI";
const Head=styled.div`background:#173e2a;color:white;padding:50px 0;h1{font-size:2.5rem;margin-bottom:7px}p{color:#c7d8cc;margin:0}`;
const Layout=styled.div`display:grid;grid-template-columns:300px 1fr;gap:25px;align-items:start;@media(max-width:750px){grid-template-columns:1fr}`;
const Side=styled(Card)`padding:25px;text-align:center;.avatar{width:92px;height:92px;background:#dfeee0;border-radius:50%;display:grid;place-items:center;color:#1d5c3a;margin:0 auto 15px}h2{font-size:1.2rem;margin-bottom:4px}p{color:#6c776f}`;
const Details=styled(Card)`padding:28px;h2{font-size:1.25rem}.row{display:grid;grid-template-columns:32px 1fr;padding:18px 0;border-bottom:1px solid #ebeeeb;gap:10px}.row svg{color:#35815a}.row small{display:block;color:#758078;margin-bottom:4px}.note{background:#f2f5f1;border-radius:12px;padding:14px;color:#69746c;font-size:.88rem;line-height:1.5;margin-top:22px}`;
export default function Profile(){const{user,logout}=useAuth();const navigate=useNavigate();const[leaving,setLeaving]=useState(false);const accountType=user.roles==="ADMIN"?"Administrador":"Cliente";const leave=()=>{setLeaving(true);logout();setTimeout(()=>navigate("/login",{replace:true}),0)};return <><Head><Container><h1>Meu perfil</h1><p>Seus dados e acesso à conta.</p></Container></Head><Section><Container><Layout><Side><div className="avatar"><UserRound size={42}/></div><h2>{user.nome}</h2><p>{accountType}</p><Button $danger onClick={leave} disabled={leaving}><LogOut size={18}/>Sair da conta</Button></Side><Details><h2>Dados pessoais</h2><div className="row"><UserRound/><div><small>Nome</small><strong>{user.nome}</strong></div></div><div className="row"><Mail/><div><small>E-mail</small><strong>{user.email}</strong></div></div><div className="row"><Phone/><div><small>Telefone</small><strong>{user.telefone}</strong></div></div><div className="row"><ShieldCheck/><div><small>Tipo de conta</small><strong>{accountType}</strong></div></div><p className="note">Para manter seus dados seguros, alterações cadastrais devem ser solicitadas pelo nosso atendimento.</p></Details></Layout></Container></Section></>}
