import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { Eye, Trash2 } from "lucide-react";
import { deleteOrder, getOrders } from "../../services/orderService";
import { getUsers } from "../../services/userService";
import { useToast } from "../../contexts/ToastContext";
import { EmptyState, ErrorState, Input, Loading, Select } from "../../components/UI";
import { AdminCard, Badge, ConfirmModal, PageHead, TableWrap, Toolbar, statusTone } from "../../components/admin/AdminUI";
import { formatCurrency, formatDate, getErrorMessage } from "../../utils/format";

export default function OrdersAdmin(){const{showToast}=useToast();const[orders,setOrders]=useState([]);const[users,setUsers]=useState([]);const[query,setQuery]=useState("");const[status,setStatus]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[target,setTarget]=useState(null);const[deleting,setDeleting]=useState(false);const load=()=>{setLoading(true);Promise.all([getOrders(),getUsers()]).then(([o,u])=>{setOrders(o);setUsers(u)}).catch(()=>setError("Não foi possível carregar os pedidos.")).finally(()=>setLoading(false))};useEffect(load,[]);const names=useMemo(()=>Object.fromEntries(users.map(u=>[u.id,u.nome])),[users]);const shown=orders.filter(o=>(!status||o.status===status)&&(`${o.id} ${names[o.cliente_id]||""}`.toLowerCase().includes(query.toLowerCase())));const remove=async()=>{setDeleting(true);try{await deleteOrder(target.id);showToast("Pedido excluído com sucesso.");setTarget(null);load()}catch(err){showToast(getErrorMessage(err),"error")}finally{setDeleting(false)}};return <><PageHead><div><h2>Pedidos</h2><p>Acompanhe todas as compras realizadas.</p></div></PageHead><Toolbar><Input placeholder="Buscar pedido ou cliente" value={query} onChange={e=>setQuery(e.target.value)}/><Select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos os status</option>{["AGUARDANDO_PAGAMENTO","PAGO","ENVIADO","ENTREGUE","CANCELADO"].map(s=><option key={s}>{s}</option>)}</Select></Toolbar>{loading?<Loading small/>:error?<ErrorState message={error} onRetry={load}/>:shown.length===0?<EmptyState title="Nenhum pedido encontrado"/>:<AdminCard><TableWrap><table><thead><tr><th>Pedido</th><th>Cliente</th><th>Data</th><th>Total</th><th>Status</th><th>Ações</th></tr></thead><tbody>{shown.map(o=><tr key={o.id}><td className="id">#{o.id}</td><td>{names[o.cliente_id]||"Cliente não encontrado"}</td><td>{formatDate(o.momento)}</td><td><strong>{formatCurrency(o.subtotal)}</strong></td><td><Badge $tone={statusTone(o.status)}>{o.status?.replaceAll("_"," ")}</Badge></td><td><div className="actions"><Link className="icon-btn" to={`/admin/pedidos/${o.id}`} title="Ver detalhes"><Eye size={17}/></Link><button className="icon-btn danger" onClick={()=>setTarget(o)} title="Excluir"><Trash2 size={17}/></button></div></td></tr>)}</tbody></table></TableWrap></AdminCard>}{target&&<ConfirmModal title="Excluir pedido" message="Essa ação removerá permanentemente o pedido e não poderá ser desfeita." loading={deleting} onCancel={()=>!deleting&&setTarget(null)} onConfirm={remove}/>}</>}
