import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import styled from "styled-components";
import { getOrderById } from "../../services/orderService";
import { getProducts } from "../../services/productService";
import { getUserById } from "../../services/userService";
import { Button, Card, ErrorState, Loading } from "../../components/UI";
import { Badge, PageHead, statusTone } from "../../components/admin/AdminUI";
import { formatCurrency, formatDate } from "../../utils/format";
const Grid=styled.div`display:grid;grid-template-columns:1fr 330px;gap:20px;@media(max-width:800px){grid-template-columns:1fr}`;
const Box=styled(Card)`padding:25px;h3{font-size:1.1rem}.item{display:grid;grid-template-columns:1fr auto;gap:15px;padding:15px 0;border-bottom:1px solid #e9ede9}.total{display:flex;justify-content:space-between;font-size:1.2rem;margin-top:20px}.row{margin:17px 0}.row small{display:block;color:#748077;margin-bottom:4px}.id{font-family:monospace;font-size:.78rem;word-break:break-all}`;
export default function OrderDetails(){const{id}=useParams();const[order,setOrder]=useState(null);const[products,setProducts]=useState([]);const[client,setClient]=useState(null);const[error,setError]=useState("");useEffect(()=>{getOrderById(id).then(async o=>{setOrder(o);const[p,c]=await Promise.all([getProducts(),getUserById(o.cliente_id)]);setProducts(p);setClient(c)}).catch(()=>setError("Não foi possível carregar este pedido."))},[id]);const names=useMemo(()=>Object.fromEntries(products.map(p=>[p.id,p.nome])),[products]);if(error)return <ErrorState message={error}/>;if(!order||!client)return <Loading small/>;return <><PageHead><div><h2>Detalhes do pedido</h2><p className="id">#{order.id}</p></div><Button $secondary as={Link} to="/admin/pedidos"><ArrowLeft size={18}/>Voltar</Button></PageHead><Grid><Box><h3>Itens do pedido</h3>{order.items?.map((item,i)=><div className="item" key={i}><div><strong>{names[item.produto_id]||"Produto"}</strong><div>{item.quantidade} × {formatCurrency(item.preco)}</div></div><strong>{formatCurrency(item.quantidade*item.preco)}</strong></div>)}<div className="total"><strong>Total</strong><strong>{formatCurrency(order.subtotal)}</strong></div></Box><Box><h3>Informações</h3><div className="row"><small>Cliente</small><strong>{client.nome}</strong></div><div className="row"><small>E-mail</small><strong>{client.email}</strong></div><div className="row"><small>Data</small><strong>{formatDate(order.momento)}</strong></div><div className="row"><small>Status</small><Badge $tone={statusTone(order.status)}>{order.status?.replaceAll("_"," ")}</Badge></div><div className="row"><small>ID do cliente</small><span className="id">{order.cliente_id}</span></div></Box></Grid></>}
