import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { Save } from "lucide-react";
import { createProduct, getProductById, updateProduct } from "../../services/productService";
import { getCategories } from "../../services/categoryService";
import { useToast } from "../../contexts/ToastContext";
import { Button, Input, Loading } from "../../components/UI";
import { FormCard, PageHead } from "../../components/admin/AdminUI";
import { getErrorMessage } from "../../utils/format";

export default function ProductForm(){const{id}=useParams();const editing=Boolean(id);const navigate=useNavigate();const{showToast}=useToast();const[categories,setCategories]=useState([]);const[form,setForm]=useState({nome:"",descricao:"",preco:"",categoriaIds:[]});const[file,setFile]=useState(null);const[loading,setLoading]=useState(editing);const[saving,setSaving]=useState(false);useEffect(()=>{Promise.all([getCategories(),editing?getProductById(id):Promise.resolve(null)]).then(([c,p])=>{setCategories(c);if(p)setForm({nome:p.nome,descricao:p.descricao,preco:p.preco,categoriaIds:p.categoriaIds||[]})}).catch(err=>showToast(getErrorMessage(err),"error")).finally(()=>setLoading(false))},[id,editing,showToast]);const toggle=cid=>setForm({...form,categoriaIds:form.categoriaIds.includes(cid)?form.categoriaIds.filter(x=>x!==cid):[...form.categoriaIds,cid]});const submit=async e=>{e.preventDefault();setSaving(true);try{if(editing){await updateProduct(id,{id,nome:form.nome,descricao:form.descricao,preco:Number(form.preco),imgUrl:null,categorias:[]});showToast("Produto atualizado com sucesso.")}else{const data=new FormData();data.append("nome",form.nome);data.append("descricao",form.descricao);data.append("preco",form.preco);data.append("imgUrl",file);form.categoriaIds.forEach(cid=>data.append("categoriaIds",cid));await createProduct(data);showToast("Produto cadastrado com sucesso.")}navigate("/admin/produtos")}catch(err){showToast(getErrorMessage(err),"error")}finally{setSaving(false)}};if(loading)return <Loading small/>;return <><PageHead><div><h2>{editing?"Editar produto":"Novo produto"}</h2><p>{editing?"O sistema atual permite alterar somente o preço.":"Preencha os dados do novo item."}</p></div></PageHead><FormCard as="form" onSubmit={submit}><div className="grid"><div className="field"><label>Nome</label><Input required disabled={editing} value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/></div><div className="field"><label>Preço</label><Input required min="0" step="0.01" type="number" value={form.preco} onChange={e=>setForm({...form,preco:e.target.value})}/></div><div className="field full"><label>Descrição</label><Input required disabled={editing} value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})}/></div>{!editing&&<><div className="field full"><label>Imagem do produto</label><Input required type="file" accept="image/*" onChange={e=>setFile(e.target.files[0])}/>{file&&<small>{file.name}</small>}</div><div className="field full"><label>Categorias</label><div className="checks">{categories.map(c=><label className="check" key={c.id}><input type="checkbox" checked={form.categoriaIds.includes(c.id)} onChange={()=>toggle(c.id)}/>{c.nome}</label>)}</div></div></>}</div><div className="buttons"><Button $secondary as={Link} to="/admin/produtos">Cancelar</Button><Button disabled={saving}><Save size={18}/>{saving?"Salvando...":"Salvar produto"}</Button></div></FormCard></>}
