import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Eye, Search, Trash2 } from "lucide-react";
import { deleteUser, getUsers } from "../../services/userService";
import { useAuth } from "../../contexts/AuthContext";
import { useToast } from "../../contexts/ToastContext";
import { EmptyState, ErrorState, Input, Loading } from "../../components/UI";
import { AdminCard, Badge, ConfirmModal, PageHead, TableWrap, Toolbar } from "../../components/admin/AdminUI";
import { getErrorMessage } from "../../utils/format";

export default function UsersAdmin(){const{user:current}=useAuth();const{showToast}=useToast();const[users,setUsers]=useState([]);const[query,setQuery]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[target,setTarget]=useState(null);const[deleting,setDeleting]=useState(false);const load=()=>{setLoading(true);getUsers().then(setUsers).catch(()=>setError("Não foi possível carregar os usuários.")).finally(()=>setLoading(false))};useEffect(load,[]);const shown=users.filter(u=>`${u.nome} ${u.email}`.toLowerCase().includes(query.toLowerCase()));const remove=async()=>{setDeleting(true);try{await deleteUser(target.id);showToast("Usuário excluído com sucesso.");setTarget(null);load()}catch(err){showToast(getErrorMessage(err),"error")}finally{setDeleting(false)}};return <><PageHead><div><h2>Usuários</h2><p>Consulte os clientes cadastrados.</p></div></PageHead><Toolbar><div style={{position:"relative",width:"100%"}}><Input placeholder="Buscar por nome ou e-mail" value={query} onChange={e=>setQuery(e.target.value)}/><Search size={18} style={{position:"absolute",right:13,top:13}}/></div></Toolbar>{loading?<Loading small/>:error?<ErrorState message={error} onRetry={load}/>:shown.length===0?<EmptyState title="Nenhum usuário encontrado"/>:<AdminCard><TableWrap><table><thead><tr><th>Nome</th><th>E-mail</th><th>Telefone</th><th>Perfil</th><th>Ações</th></tr></thead><tbody>{shown.map(u=><tr key={u.id}><td><strong>{u.nome}</strong></td><td>{u.email}</td><td>{u.telefone}</td><td><Badge $tone={u.roles==="ADMIN"?"info":"success"}>{u.roles==="ADMIN"?"Administrador":"Cliente"}</Badge></td><td><div className="actions"><Link className="icon-btn" to={`/admin/usuarios/${u.id}`} title="Detalhes"><Eye size={17}/></Link>{u.id!==current.id&&<button className="icon-btn danger" onClick={()=>setTarget(u)} title="Excluir"><Trash2 size={17}/></button>}</div></td></tr>)}</tbody></table></TableWrap></AdminCard>}{target&&<ConfirmModal title="Excluir usuário" message={`Tem certeza de que deseja excluir a conta de ${target.nome}?`} loading={deleting} onCancel={()=>!deleting&&setTarget(null)} onConfirm={remove}/>}</>}
